management:
  endpoints:
    web:
      exposure.include: "*"
      base-path: /


spring.servlet.multipart.max-file-size : 100MB
spring.servlet.multipart.max-request-size : 1000MB
server:
  port: 9001
spring:
  application:
    name: its
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
elasticsearch: false

logging:
  file: /home/log/springboot-${spring.application.name}.log

druid:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时的时间
    maxWait: 600000
    #超过时间限制是否回收
    removeAbandoned: true
    #超过时间限制多长
    removeAbandonedTimeout: 180
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 600000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
    filters: log4j

devtools:
    restart:
    enabled: true #是否开启开发者工具（true/false）
    additional-paths: src/main/java
    exclude: static/**

